// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessoRistretto.Models;

namespace ProcessoRistretto.Migrations
{
    [DbContext(typeof(RistrettoContext))]
    partial class RistrettoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProcessoRistretto.Models.Empresa", b =>
                {
                    b.Property<long>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_EMPRESA")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("DddTelefone")
                        .HasColumnName("TELEFONE_1")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeEmpresarial")
                        .HasColumnName("NOME_EMPRESARIAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnName("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmpresa");

                    b.ToTable("EMPRESA");
                });

            modelBuilder.Entity("ProcessoRistretto.Models.Funcionario", b =>
                {
                    b.Property<long>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_FUNCIONARIO")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnName("DT_NASCIMENTO")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .HasColumnName("LOGIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnName("NOME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Senha")
                        .HasColumnName("SENHA")
                        .HasColumnType("bigint");

                    b.Property<string>("Sobrenome")
                        .HasColumnName("SOBRENOME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnName("STATUS")
                        .HasColumnType("bit");

                    b.HasKey("IdFuncionario");

                    b.ToTable("FUNCIONARIO");
                });
#pragma warning restore 612, 618
        }
    }
}
